### ISSUE TITLE
MT-CBENCH usage

### ISSUE THREAD

**Issue by rmrosario** [intracom-telecom-sdn/mtcbench#4]
I have a small SDN testbed for experimentation purposes. I would like make various stress tests on the controllers that I have installed. I am trying to build “build_mtcbench.sh” on an Ubuntu 14.4 LTS, and it seems that the process went fine, but I am not sure how to issue the actual usage commands. Can you please provide an example?

**Comment by rmrosario** [comment]
Adding to this thread.. I am trying to make it work with ODL Lithium.

**Comment by anastop** [comment]
Hi, 

First, to experiment with ODL Lithium, a good starting point is to use the Lithium handlers provided in the NSTAT tool repo. Specifically, [start_droptestDS.sh](https://github.com/intracom-telecom-sdn/nstat/blob/master/controllers/odl_lithium_sr3_pb/start_droptestDS.sh) and [start_droptestRPC.sh](https://github.com/intracom-telecom-sdn/nstat/blob/master/controllers/odl_lithium_sr3_pb/start_droptestRPC.sh) start the ODL controller with the "drop-test" feature (needed to play with MT-/Cbench) on "DataStore" and "RPC" mode, respectively. 

Now, as for a sample usage, after MTCbench is built, you can issue a command like the following to produce relatively intense traffic:

```
./oflops/cbench/cbench -c 127.0.0.1 -l 1 -M 100 -m 200000 -p 6653 -w 0 -S 50 -T 15000 -D 15000 -Z 2
```

This triggers controller responses that have been verified to be as high as ~100K per second in our experimental setup, and with MT-Cbench operating in Latency mode. Please have a look at MT-Cbench help message for a detailed description of each cmd line argument. 

For other possible usages, I would suggest having a look at our [Performance Reports](https://github.com/intracom-telecom-sdn/nstat#browse-performance-results), and specifically at the test cases where MT-Cbench is involved. The detailed configurations from these results are also available in NSTAT repo, under the folder `stress_test/stress_test_confs` (e.g. have a look [here](https://github.com/intracom-telecom-sdn/nstat/tree/master/stress_test/stress_test_confs/lithium_sr3) for Lithium SR3 test configurations)
